wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.30
      6: 4.6.1
      8:
      - 1
      - 5
asset_dir:
  desc: null
  value: asset
batch_size:
  desc: null
  value: 64
clip_grad:
  desc: null
  value: 10
data_dir:
  desc: null
  value: /opt/ml/input/data/train_dataset
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.2
hidden_dim:
  desc: null
  value: 64
log_steps:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
max_seq_len:
  desc: null
  value: 20
model:
  desc: null
  value: lstm
model_dir:
  desc: null
  value: models
model_name:
  desc: null
  value: model.pt
n_epochs:
  desc: null
  value: 20
n_layers:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: adam
output_dir:
  desc: null
  value: output
patience:
  desc: null
  value: 5
scheduler:
  desc: null
  value: plateau
seed:
  desc: null
  value: 42
